CREATE DATABASE BarberDevs

USE BarberDevs

CREATE TABLE TipoUsuario(
IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeTipoUsuario VARCHAR(200)
);

CREATE TABLE Barbearia(
IdBarbearia UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeFantasia VARCHAR(100),
CNPJ VARCHAR(100),
Latitude DECIMAL(8,6),
Longitude DECIMAL(9,6),
Cep VARCHAR(100),
Logradouro VARCHAR(100),
Bairro VARCHAR(100),
Numero VARCHAR(10)
);

CREATE TABLE Usuario(
IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(250) NOT NULL UNIQUE,
Senha VARCHAR(250) NOT NULL,
Foto TEXT,
Rg VARCHAR(100),
Cpf VARCHAR(100)
);

CREATE TABLE Barbeiro(
IdBarbeiro UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
IdBarbearia UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Barbearia(IdBarbearia),
Descricao TEXT
);

CREATE TABLE Cliente(
IdCliente UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario)
);

CREATE TABLE Agendamento(
IdAgendamento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdBarbeiro UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Barbeiro(IdBarbeiro),
IdCliente UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Cliente(IdCliente),
DataAgendamento DATETIME
);

--Scaffold-DbContext "Data Source=DESKTOP-RIHPD9E\SQLEXPRESS; initial catalog=BarberDevs; User Id = sa; pwd = senhavinip140805; TrustServerCertificate=true;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Domains -ContextDir Contexts -Context BarberDevsContext -f